### ISSUE TITLE
Sometimes vscode establishes a new connection to the vm if a tab is changed

### ISSUE THREAD

**Issue by tipue-dev** [dennykorsukewitz/DK4Znuny-VisualStudioCode#3]
# Bug report

## Expected behavior

Changing between tabs should never reload vscode, or its connection to the remote host.

## Actual behavior

Sometimes (not reliably reproducible) when changing a tab, vscode flashed to black and establishes a new connection to the vm.

## How to reproduce

Not reliably reproducible

## Screenshots

I may be able to record it on video, but i would have to create a workspace without customer data and a few tries.
Let me know if you think a video might help.

## Environment

- Host OS: Windows
- VM OS: Ubuntu 22.04
- Connection to the VM via the addon "Remote - SSH"
- The workspace contains several directories that are added to the workspace

## Additional information

This problem was noticed after the functionality that shows the Znuny-Version in the status bar.
The Problem stopped occurring on a colleagues maschine after he deactivated the addon a few weeks ago.
He and I have the same setup otherwise, so i can't say what factors into the problem.
It can happen often, like several times per hour, or not once on some days.
There are no errors shown in the terminal.

**Comment by dennykorsukewitz** [comment]
Hi  @tipue-dev ,
thanks for your report.

I have found some code that may cause the StatusBar to be executed too often.
Perhaps this will break the connection.

- https://github.com/dennykorsukewitz/VSCode-Znuny/blob/dev/package.json#L34-L37
- https://github.com/dennykorsukewitz/VSCode-Znuny/blob/dev/src/extension.js#L145

This will be improved in the next version.

Furthermore you can set when the StatusBar should be updated in the settings. 
(znuny.statusBar.enabled)

- "Always active."
- "Activated only by a command".
- "Activated only when the active TextEditor is changed."
- "Not active."

Version 1.1.0 is coming soon.

Regards :rocket:
Denny

**Comment by dennykorsukewitz** [comment]
Hi @tipue-dev ,

[Version 1.1.0](https://github.com/dennykorsukewitz/VSCode-Znuny/releases/tag/1.1.0) is released.

As I wrote in the previous comment, I have changed some things.

Furthermore you can set when the StatusBar should be updated in the settings.
(znuny.statusBar.enabled)

"Always active."
"Activated only by a command".
"Activated only when the active TextEditor is changed."
"Not active."

I will close the issue. If you still have the error, just write.

Regards 🚀
Denny
